// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PersonProto3.proto

package com.example.demo.proto;

public interface Person3OrBuilder extends
    // @@protoc_insertion_point(interface_extends:Person3)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 5;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>int32 age = 1;</code>
   * @return The age.
   */
  int getAge();

  /**
   * <code>.google.protobuf.Int32Value height = 2;</code>
   * @return Whether the height field is set.
   */
  boolean hasHeight();
  /**
   * <code>.google.protobuf.Int32Value height = 2;</code>
   * @return The height.
   */
  com.google.protobuf.Int32Value getHeight();
  /**
   * <code>.google.protobuf.Int32Value height = 2;</code>
   */
  com.google.protobuf.Int32ValueOrBuilder getHeightOrBuilder();

  /**
   * <code>string job_name = 3;</code>
   * @return The jobName.
   */
  String getJobName();
  /**
   * <code>string job_name = 3;</code>
   * @return The bytes for jobName.
   */
  com.google.protobuf.ByteString
      getJobNameBytes();

  /**
   * <pre>
   * required string name = 4;
   * </pre>
   *
   * <code>repeated string cars = 4;</code>
   * @return A list containing the cars.
   */
  java.util.List<String>
      getCarsList();
  /**
   * <pre>
   * required string name = 4;
   * </pre>
   *
   * <code>repeated string cars = 4;</code>
   * @return The count of cars.
   */
  int getCarsCount();
  /**
   * <pre>
   * required string name = 4;
   * </pre>
   *
   * <code>repeated string cars = 4;</code>
   * @param index The index of the element to return.
   * @return The cars at the given index.
   */
  String getCars(int index);
  /**
   * <pre>
   * required string name = 4;
   * </pre>
   *
   * <code>repeated string cars = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the cars at the given index.
   */
  com.google.protobuf.ByteString
      getCarsBytes(int index);
}
